<?xml version="1.0" encoding="utf-8"?><Database Name="CSM" Class="CSM_DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="ChiTietDonHangID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DonHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SanPhamID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="DonHangID" OtherKey="DonHangID" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="SanPhamID" OtherKey="SanPhamID" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhToan" Member="ThanhToans">
    <Type Name="ThanhToan">
      <Column Name="ThanhToanID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DonHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HinhThucThanhToan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangThanhToan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DonHang_ThanhToan" Member="DonHang" ThisKey="DonHangID" OtherKey="DonHangID" Type="DonHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="DanhMucID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="DanhMuc_SanPham" Member="SanPhams" ThisKey="DanhMucID" OtherKey="DanhMucID" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="DonHangID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NguoiDungID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TongTien" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrangDonHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDatHang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaChiGiaoHang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="DonHangID" OtherKey="DonHangID" Type="ChiTietDonHang" />
      <Association Name="DonHang_ThanhToan" Member="ThanhToans" ThisKey="DonHangID" OtherKey="DonHangID" Type="ThanhToan" />
      <Association Name="NguoiDung_DonHang" Member="NguoiDung" ThisKey="NguoiDungID" OtherKey="NguoiDungID" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GioHang" Member="GioHangs">
    <Type Name="GioHang">
      <Column Name="GioHangID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NguoiDungID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SanPhamID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NguoiDung_GioHang" Member="NguoiDung" ThisKey="NguoiDungID" OtherKey="NguoiDungID" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="SanPham_GioHang" Member="SanPham" ThisKey="SanPhamID" OtherKey="SanPhamID" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="NguoiDungID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoThich" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PhanKhucKH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Train" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="KichHoat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="NguoiDung_DonHang" Member="DonHangs" ThisKey="NguoiDungID" OtherKey="NguoiDungID" Type="DonHang" />
      <Association Name="NguoiDung_GioHang" Member="GioHangs" ThisKey="NguoiDungID" OtherKey="NguoiDungID" Type="GioHang" />
      <Association Name="NguoiDung_PhanHoi" Member="PhanHois" ThisKey="NguoiDungID" OtherKey="NguoiDungID" Type="PhanHoi" />
    </Type>
  </Table>
  <Table Name="dbo.PhanHoi" Member="PhanHois">
    <Type Name="PhanHoi">
      <Column Name="PhanHoiID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SanPhamID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NguoiDungID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DanhGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayPhanHoi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="NguoiDung_PhanHoi" Member="NguoiDung" ThisKey="NguoiDungID" OtherKey="NguoiDungID" Type="NguoiDung" IsForeignKey="true" />
      <Association Name="SanPham_PhanHoi" Member="SanPham" ThisKey="SanPhamID" OtherKey="SanPhamID" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="SanPhamID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongTonKho" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DanhMucID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnhUrl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KichHoat" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="SanPhamID" OtherKey="SanPhamID" Type="ChiTietDonHang" />
      <Association Name="SanPham_GioHang" Member="GioHangs" ThisKey="SanPhamID" OtherKey="SanPhamID" Type="GioHang" />
      <Association Name="SanPham_PhanHoi" Member="PhanHois" ThisKey="SanPhamID" OtherKey="SanPhamID" Type="PhanHoi" />
      <Association Name="DanhMuc_SanPham" Member="DanhMuc" ThisKey="DanhMucID" OtherKey="DanhMucID" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>